LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := matrix_32
LOCAL_CPPFLAGS := -DNDEBUG
LOCAL_CFLAGS += -DNDEBUG
LOCAL_SRC_FILES := src/DAEMON_32/main.cpp \
LOCAL_CPP_INCLUDES += $(LOCAL_PATH)
LOCAL_LDLIBS += -llog
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_MODULE := matrix_64
LOCAL_CPPFLAGS := -DNDEBUG
LOCAL_CFLAGS += -DNDEBUG
LOCAL_SRC_FILES := src/DAEMON_64/main.cpp \
LOCAL_CPP_INCLUDES += $(LOCAL_PATH)
LOCAL_LDLIBS += -llog
include $(BUILD_EXECUTABLE)