package com.cp.jo.enums;

public enum CallbackRequest {
    DOWN, SUCCESSFUL, MAINTENANCE, EXCEPTION, ERROR, INVALID, UPDATE, ALREADY_HAVE_ACCOUNT_NO_VERIFIED, IS_BAN, ALREADY_HAVE_ACCOUNT, NO_VERIFIED, EXPIRATION, DONE_KEY, USED
}
