package com.cp.jo.enums;

public enum SendCPP {
    //-- Drawing For Player
    LINE, SKELETON, INFO_PLAYER, WEAPON, MARK, HEALTH, GRENADE, BOX1, DIST, //-- MEMORY
    LESS, CROSS, AIMBOT_SDK, IPAD_VIEW, IS_AIMBOT, IS_BULLET, IS_BOT_AIMBOT, IS_KNOCK_AIMBOT, FOV_AIMBOT, DIST_AIMBOT, PRIORITY_AIMBOT, TARGET_AIMBOT, OFFSET_SCOPE, OFFSET_NO_SCOPE, //-- CONTROLS
    WIDTH_LINE, RADIUS360, SIZE_ITEM, SIZE_VEHICLE, SIZE_INFO, UP_INFO, //-- RIGHTS
    EMAIL, PASSWORD, PATH, _NULL, //-- Other
    HIDE_ITEMS, //--Items
    //item
    DROP, BOX, COINS, FLARE_GUN, //Ar
    AKM, M16A4, SCAR_L, M416, GROZA, AUG, QBZ, M762, MK47, _636C, FAMAS, //Sr
    KAR98K, M24, AWM, WIN94, MOSIN, //Dmr
    SKS, VSS, MINI14, MK14, SLR, QUB, MK12, //Smg
    UZI, UMP45, VECTOR, BIZON, THOMPSON, MP5K, P90, //Shotgun
    S686, S1897, S12K, DBS, M1014, //Lmg
    M249, DP_28, M163, //scope
    x8, x6, x4, x3, x2, RED_POINT, //Melee
    PAN, MACHETE, CROWBAR, SICKLE, //Other
    CROSSBOW, //Helmet
    HELMET_LV1, HELMET_LV2, HELMET_LV3, //armor
    ARMOR_LV1, ARMOR_LV2, ARMOR_LV3, //Backpack
    BACKPACK_LV1, BACKPACK_LV2, BACKPACK_LV3, //MadKit
    ENERGY, ADRENALINE, PAINKILLER, BANDAGES, FIRST, MADKIT, FUEL, //Muzzle
    COMPENSATOR, VERTICAL, EQ_AR, EQ_SP, EQ_SMG, E_AR, E_SP, E_SMG, //Vehicle
    UAZ, BRDM, BUS, UTV, MONSTER, PICKUP, RONY, DACIA, COUPE, MIRADO, TUKSHAI, SIDECAR, SNOWMOBILE, SNOWBIKE, MOTORCYCIE, SCOOTER, BUGGY, GILDER, PG117, AQUAPAIL, BICYCLE
}


